import type { AppUserProfile } from './authProfile';

type MockUser = AppUserProfile & { created_at: string };

// Reactive in-memory store for the current dev session user.
// Resets on page reload — no backend or localStorage involved.
let _currentProfile: AppUserProfile | null = null;
const _listeners = new Set<() => void>();

export const devStore = {
  getProfile: () => _currentProfile,
  setProfile: (p: AppUserProfile | null) => {
    _currentProfile = p;
    _listeners.forEach(fn => fn());
  },
  subscribe: (fn: () => void) => {
    _listeners.add(fn);
    return () => _listeners.delete(fn);
  },
};

export const DEV_MOCK_USERS: MockUser[] = [
  // ── EMPRESAS (17) ──────────────────────────────────────────────────────────
  { id: 1,  clerk_user_id: 'mock-e-01', role: 'empresa', fullname: 'Carlos Mendoza Rivera',    email: 'cmendoza@logpacific.pe',      company_name: 'Logística Pacific S.A.C.',                  industry: 'logistica',      activity_type: 'Almacenamiento y distribución de carga',            space_required: '8000',  energy_required: '350',  location: 'Av. Principal 100, Chancay',              created_at: '2025-08-15T10:30:00Z' },
  { id: 2,  clerk_user_id: 'mock-e-02', role: 'empresa', fullname: 'Ana Torres Villanueva',     email: 'atorres@manufnorte.com',      company_name: 'Manufacturas Industriales del Norte S.A.',   industry: 'manufactura',    activity_type: 'Fabricación de envases de plástico',                space_required: '5000',  energy_required: '500',  location: 'Sector Industrial Norte, Chancay',        created_at: '2025-09-02T08:15:00Z' },
  { id: 3,  clerk_user_id: 'mock-e-03', role: 'empresa', fullname: 'Roberto Suárez Castillo',   email: 'rsuarez@agrochan.pe',         company_name: 'Agroindustrias Chancay S.R.L.',              industry: 'agroindustrial', activity_type: 'Procesamiento y exportación de espárragos',         space_required: '12000', energy_required: '400',  location: 'Km 82 Panamericana Norte, Chancay',       created_at: '2025-09-18T14:00:00Z' },
  { id: 4,  clerk_user_id: 'mock-e-04', role: 'empresa', fullname: 'María Quispe Huamán',       email: 'mquispe@energiasolar.pe',     company_name: 'Energía Solar Perú S.A.C.',                 industry: 'energia',        activity_type: 'Instalación y operación de paneles solares',        space_required: '20000', energy_required: '100',  location: 'Zona Logística Este, Huaral',             created_at: '2025-10-05T09:45:00Z' },
  { id: 5,  clerk_user_id: 'mock-e-05', role: 'empresa', fullname: 'Diego Flores Paredes',      email: 'dflores@techport.pe',         company_name: 'TechPort Innovaciones S.A.C.',               industry: 'tecnologia',     activity_type: 'Sistemas de gestión portuaria y trazabilidad',      space_required: '1500',  energy_required: '200',  location: 'Parque Industrial Central, Chancay',      created_at: '2025-10-22T11:20:00Z' },
  { id: 6,  clerk_user_id: 'mock-e-06', role: 'empresa', fullname: 'Sofía Vargas Delgado',      email: 'svargas@portoinmob.pe',       company_name: 'Inmobiliaria Porto Chancay S.A.C.',          industry: 'inmobiliaria',   activity_type: 'Desarrollo de parques industriales y logísticos',   space_required: '50000', energy_required: '1000', location: 'Av. Principal 580, Chancay',              created_at: '2025-11-08T16:00:00Z' },
  { id: 7,  clerk_user_id: 'mock-e-07', role: 'empresa', fullname: 'Javier Morales Chávez',     email: 'jmorales@transpac.pe',        company_name: 'Transportes del Pacífico S.A.',             industry: 'logistica',      activity_type: 'Transporte multimodal y distribución nacional',     space_required: '6000',  energy_required: '280',  location: 'Terminal Logístico, Chancay',             created_at: '2025-11-25T08:30:00Z' },
  { id: 8,  clerk_user_id: 'mock-e-08', role: 'empresa', fullname: 'Carmen Huanca Quispe',      email: 'chuanca@textandes.com',       company_name: 'Industrias Textiles Andinas S.A.C.',        industry: 'manufactura',    activity_type: 'Confección y exportación de prendas de algodón',   space_required: '7000',  energy_required: '600',  location: 'Sector Industrial Sur, Chancay',          created_at: '2025-12-10T10:00:00Z' },
  { id: 9,  clerk_user_id: 'mock-e-09', role: 'empresa', fullname: 'Luis Paredes Soto',         email: 'lparedes@agrohuaral.pe',      company_name: 'Agroexport Huaral S.A.C.',                  industry: 'agroindustrial', activity_type: 'Exportación de frutas y hortalizas frescas',        space_required: '9000',  energy_required: '320',  location: 'Km 75 Panamericana Norte, Huaral',        created_at: '2026-01-05T14:30:00Z' },
  { id: 10, clerk_user_id: 'mock-e-10', role: 'empresa', fullname: 'Patricia Díaz Luna',        email: 'pdiaz@minergiacen.pe',        company_name: 'Minería y Energía del Centro S.A.',         industry: 'energia',        activity_type: 'Operación de planta termoeléctrica',               space_required: '25000', energy_required: '5000', location: 'Zona Industrial Norte, Chancay',          created_at: '2026-01-20T09:15:00Z' },
  { id: 11, clerk_user_id: 'mock-e-11', role: 'empresa', fullname: 'André Benavides Ruiz',      email: 'abenavides@digitport.pe',     company_name: 'Digital Port Solutions S.A.C.',             industry: 'tecnologia',     activity_type: 'Automatización IoT para operaciones portuarias',   space_required: '800',   energy_required: '150',  location: 'Centro Empresarial, Chancay',             created_at: '2026-02-08T13:45:00Z' },
  { id: 12, clerk_user_id: 'mock-e-12', role: 'empresa', fullname: 'Rosa Castillo Mendoza',     email: 'rcastillo@desindlima.pe',     company_name: 'Desarrollos Industriales Lima S.A.',        industry: 'inmobiliaria',   activity_type: 'Construcción de naves industriales y almacenes',   space_required: '30000', energy_required: '800',  location: 'Av. Industrial 200, Chancay',             created_at: '2026-02-25T08:00:00Z' },
  { id: 13, clerk_user_id: 'mock-e-13', role: 'empresa', fullname: 'Fernando Ríos Vásquez',     email: 'frios@almacesglobal.pe',      company_name: 'Almacenes Globales del Perú S.A.C.',        industry: 'logistica',      activity_type: 'Operación de centros de distribución',             space_required: '15000', energy_required: '450',  location: 'Parque Logístico Chancay, Chancay',       created_at: '2026-03-05T11:30:00Z' },
  { id: 14, clerk_user_id: 'mock-e-14', role: 'empresa', fullname: 'Valentina Cruz Peña',       email: 'vcruz@procesalim.pe',         company_name: 'Procesadora de Alimentos del Norte S.A.C.', industry: 'agroindustrial', activity_type: 'Conservas y alimentos congelados para exportación',space_required: '10000', energy_required: '700',  location: 'Zona Agroindustrial, Huaral',             created_at: '2026-03-18T14:00:00Z' },
  { id: 15, clerk_user_id: 'mock-e-15', role: 'empresa', fullname: 'Héctor Salinas Quiroz',     email: 'hsalinas@corpagri.pe',        company_name: 'Corporación Agrícola Chancay S.A.C.',       industry: 'agroindustrial', activity_type: 'Cultivo y exportación de palto y cítricos',        space_required: '5000',  energy_required: '200',  location: 'Valle de Chancay, Huaral',                created_at: '2026-03-28T09:00:00Z' },
  { id: 16, clerk_user_id: 'mock-e-16', role: 'empresa', fullname: 'Gabriela Mendoza Tello',    email: 'gmendoza@petgasnorte.pe',     company_name: 'Petróleo y Gas Costa Norte S.A.C.',         industry: 'energia',        activity_type: 'Almacenamiento y distribución de combustibles',    space_required: '18000', energy_required: '600',  location: 'Terminal Portuario, Chancay',             created_at: '2026-04-05T10:15:00Z' },
  { id: 17, clerk_user_id: 'mock-e-17', role: 'empresa', fullname: 'Martín Torres Espinoza',    email: 'mtorres@solport.pe',          company_name: 'Soluciones Portuarias Digitales S.R.L.',    industry: 'tecnologia',     activity_type: 'Software de gestión aduanera y logística',        space_required: '600',   energy_required: '100',  location: 'Centro Empresarial Porto, Chancay',       created_at: '2026-04-15T14:30:00Z' },

  // ── PROPIETARIOS (17) ──────────────────────────────────────────────────────
  { id: 18, clerk_user_id: 'mock-p-01', role: 'propietario', fullname: 'José Ramírez Oliva',      email: 'jramirez.prop@chancay.pe',  type: 'industrial', location: 'Lote A-12, Zona Industrial Norte, Chancay',        size: '15000', services: 'Terreno plano con acceso a red eléctrica trifásica',                    created_at: '2025-08-20T10:00:00Z' },
  { id: 19, clerk_user_id: 'mock-p-02', role: 'propietario', fullname: 'Elena Vargas Campos',      email: 'evargas.prop@chancay.pe',   type: 'logistico',  location: 'Sector Logístico B, Km 80, Chancay',               size: '25000', services: 'Plataforma pavimentada y estacionamiento para camiones',               created_at: '2025-09-10T11:30:00Z' },
  { id: 20, clerk_user_id: 'mock-p-03', role: 'propietario', fullname: 'Manuel Chávez Quispe',     email: 'mchavez.prop@chancay.pe',   type: 'industrial', location: 'Parque Industrial Central, Lote 23, Chancay',       size: '8500',  services: 'Conexión de agua, desagüe y energía trifásica instalada',              created_at: '2025-09-28T09:45:00Z' },
  { id: 21, clerk_user_id: 'mock-p-04', role: 'propietario', fullname: 'Lucía Ortiz Herrera',      email: 'lortiz.prop@chancay.pe',    type: 'comercial',  location: 'Av. Principal 450, Chancay',                        size: '3000',  services: 'Local comercial frente a avenida principal, 2 pisos',                  created_at: '2025-10-15T14:00:00Z' },
  { id: 22, clerk_user_id: 'mock-p-05', role: 'propietario', fullname: 'Ricardo Flores Pinto',     email: 'rflores.prop@chancay.pe',   type: 'industrial', location: 'Zona Franca Industrial, Lote 7, Chancay',           size: '20000', services: 'Terreno rectangular con acceso a vías de primer orden',               created_at: '2025-11-02T08:00:00Z' },
  { id: 23, clerk_user_id: 'mock-p-06', role: 'propietario', fullname: 'Sandra Torres Mamani',     email: 'storres.prop@chancay.pe',   type: 'logistico',  location: 'Terminal Logístico Norte, Lote 15, Chancay',        size: '35000', services: 'Gran terreno habilitado para almacén y patio de maniobras',            created_at: '2025-11-20T10:30:00Z' },
  { id: 24, clerk_user_id: 'mock-p-07', role: 'propietario', fullname: 'Alberto Morales Sánchez',  email: 'amorales.prop@chancay.pe',  type: 'industrial', location: 'Sector Industrial Sur, Lote 8, Chancay',            size: '12000', services: 'Terreno con nave existente de 3 000 m²',                               created_at: '2025-12-05T13:15:00Z' },
  { id: 25, clerk_user_id: 'mock-p-08', role: 'propietario', fullname: 'Carmen Díaz Llanos',       email: 'cdiaz.prop@chancay.pe',     type: 'mixto',      location: 'Av. Industrial 600, Chancay',                       size: '6000',  services: 'Terreno mixto uso industrial y comercial autorizado',                  created_at: '2025-12-22T09:00:00Z' },
  { id: 26, clerk_user_id: 'mock-p-09', role: 'propietario', fullname: 'Hugo Salcedo Prado',       email: 'hsalcedo.prop@chancay.pe',  type: 'logistico',  location: 'Km 82, Panamericana Norte, Huaral',                 size: '18000', services: 'Centro de distribución, fácil acceso a autopista',                     created_at: '2026-01-08T11:00:00Z' },
  { id: 27, clerk_user_id: 'mock-p-10', role: 'propietario', fullname: 'Mónica Quispe Arredondo',  email: 'mquispe.prop@chancay.pe',   type: 'industrial', location: 'Zona Industrial Este, Lote 45, Chancay',            size: '9500',  services: 'Terreno industrial con suministro de agua industrial',                 created_at: '2026-01-25T14:30:00Z' },
  { id: 28, clerk_user_id: 'mock-p-11', role: 'propietario', fullname: 'Gonzalo Peña Torres',      email: 'gpena.prop@chancay.pe',     type: 'industrial', location: 'Parque Industrial II, Lote 3, Chancay',             size: '22000', services: 'Terreno llano con energía trifásica y acceso a gas natural',          created_at: '2026-02-10T08:45:00Z' },
  { id: 29, clerk_user_id: 'mock-p-12', role: 'propietario', fullname: 'Inés Castillo Navarro',    email: 'icastillo.prop@chancay.pe', type: 'logistico',  location: 'Sector Puerto, Lote 2, Chancay',                    size: '45000', services: 'Gran terreno lindante al área portuaria con fácil acceso',            created_at: '2026-02-28T10:00:00Z' },
  { id: 30, clerk_user_id: 'mock-p-13', role: 'propietario', fullname: 'Omar Huanca Vilca',        email: 'ohuanca.prop@chancay.pe',   type: 'industrial', location: 'Zona Agroindustrial, Lote 12, Huaral',              size: '7800',  services: 'Planta de agua propia y cerco perimétrico completo',                   created_at: '2026-03-08T13:30:00Z' },
  { id: 31, clerk_user_id: 'mock-p-14', role: 'propietario', fullname: 'Patricia Espinoza Cruz',   email: 'pespinoza.prop@chancay.pe', type: 'comercial',  location: 'Centro Comercial Porto, Local 8, Chancay',          size: '1200',  services: 'Acceso peatonal y vehicular, ubicado cerca al puerto',                 created_at: '2026-03-20T09:15:00Z' },
  { id: 32, clerk_user_id: 'mock-p-15', role: 'propietario', fullname: 'Ramón Valdivia Reyes',     email: 'rvaldivia.prop@chancay.pe', type: 'mixto',      location: 'Av. Los Industriales 120, Chancay',                 size: '11000', services: 'Terreno esquinero doble acceso, uso mixto autorizado',                 created_at: '2026-04-01T10:30:00Z' },
  { id: 33, clerk_user_id: 'mock-p-16', role: 'propietario', fullname: 'Claudia Ramos Bejarano',   email: 'cramos.prop@chancay.pe',    type: 'industrial', location: 'Lote Industrial C-7, Zona Norte, Chancay',          size: '16500', services: 'Terreno habilitado con plataforma de concreto',                        created_at: '2026-04-10T14:00:00Z' },
  { id: 34, clerk_user_id: 'mock-p-17', role: 'propietario', fullname: 'Felipe Aguilar Meza',      email: 'faguilar.prop@chancay.pe',  type: 'logistico',  location: 'Terminal de Carga, Sector 4, Chancay',              size: '28000', services: 'Cámaras de seguridad y vigilancia 24 h incluidas',                     created_at: '2026-04-18T11:00:00Z' },

  // ── PROVEEDORES (16) ──────────────────────────────────────────────────────
  { id: 35, clerk_user_id: 'mock-v-01', role: 'proveedor', fullname: 'Miguel Ángel Peralta Ruiz',  email: 'mperalta@consultec.pe',      company_name: 'ConsulTec Ingeniería S.A.C.',             services: 'Consultoría técnica y estudios de prefactibilidad industrial', experience: '15',  location: 'Lima / Chancay',          created_at: '2025-08-25T09:30:00Z' },
  { id: 36, clerk_user_id: 'mock-v-02', role: 'proveedor', fullname: 'Silvia Núñez Alvarado',      email: 'snunez@juridicaport.pe',     company_name: 'Jurídica Porto & Asociados',             services: 'Asesoría legal en contratos de inversión, licencias y permisos', experience: '12', location: 'Chancay / Huaral',       created_at: '2025-09-15T11:00:00Z' },
  { id: 37, clerk_user_id: 'mock-v-03', role: 'proveedor', fullname: 'Arturo Cárdenas Vela',       email: 'acardenas@constrchan.pe',    company_name: 'Construcciones Chancay S.R.L.',          services: 'Supervisión de obra, movimiento de tierras y habilitación', experience: '20',         location: 'Chancay',                created_at: '2025-10-01T14:30:00Z' },
  { id: 38, clerk_user_id: 'mock-v-04', role: 'proveedor', fullname: 'Natalia Rojas Esteban',      email: 'nrojas@logistilink.pe',      company_name: 'LogistiLink del Perú S.A.C.',            services: 'Gestión de almacenes, control de inventarios y distribución', experience: '8',   location: 'Chancay / Lima Norte',    created_at: '2025-10-18T10:00:00Z' },
  { id: 39, clerk_user_id: 'mock-v-05', role: 'proveedor', fullname: 'Enrique Soto Bravo',         email: 'esoto@energiaindustrial.pe', company_name: 'Energía Industrial Perú S.A.C.',         services: 'Instalaciones eléctricas industriales y mantenimiento', experience: '18',              location: 'Chancay / Huaral / Lima', created_at: '2025-11-05T09:00:00Z' },
  { id: 40, clerk_user_id: 'mock-v-06', role: 'proveedor', fullname: 'Daniela Chávez Estrada',     email: 'dchavez@ambiental360.pe',    company_name: 'Ambiental 360 S.A.C.',                  services: 'Estudios de impacto ambiental, EIA y consultoría de sostenibilidad', experience: '10', location: 'Lima / Chancay',         created_at: '2025-11-22T13:00:00Z' },
  { id: 41, clerk_user_id: 'mock-v-07', role: 'proveedor', fullname: 'Guillermo Navarro Quiroz',   email: 'gnavarro@manteindustrial.pe',company_name: 'Manteindustrial S.A.C.',                 services: 'Mantenimiento preventivo y correctivo de maquinaria industrial', experience: '14', location: 'Chancay',                created_at: '2025-12-08T10:30:00Z' },
  { id: 42, clerk_user_id: 'mock-v-08', role: 'proveedor', fullname: 'Paola Gutiérrez Sánchez',    email: 'pgutierrez@aduana360.pe',    company_name: 'Aduanas 360 Agentes S.A.C.',             services: 'Agencia de aduanas, despacho de importaciones y exportaciones', experience: '16', location: 'Chancay / Callao',        created_at: '2025-12-24T09:15:00Z' },
  { id: 43, clerk_user_id: 'mock-v-09', role: 'proveedor', fullname: 'Sergio Mendívil Torres',     email: 'smendivil@arqindustrial.pe', company_name: 'Arquitectura Industrial del Norte S.A.C.',services: 'Diseño y construcción de naves industriales y almacenes', experience: '22',    location: 'Lima / Chancay',          created_at: '2026-01-12T14:00:00Z' },
  { id: 44, clerk_user_id: 'mock-v-10', role: 'proveedor', fullname: 'Alejandra Fuentes Quispe',   email: 'afuentes@seguriport.pe',     company_name: 'SeguriPort del Perú S.A.C.',             services: 'Seguridad y vigilancia para instalaciones industriales y portuarias', experience: '9', location: 'Chancay',               created_at: '2026-01-28T11:30:00Z' },
  { id: 45, clerk_user_id: 'mock-v-11', role: 'proveedor', fullname: 'Bernardo Salas Campos',      email: 'bsalas@finanzasinvers.pe',   company_name: 'Finanzas & Inversiones S.R.L.',          services: 'Estructuración financiera, valoración de proyectos e inversión', experience: '13', location: 'Lima / Chancay',         created_at: '2026-02-15T09:45:00Z' },
  { id: 46, clerk_user_id: 'mock-v-12', role: 'proveedor', fullname: 'Isabel Villanueva Peña',     email: 'ivillanueva@rrhh360.pe',     company_name: 'Recursos Humanos 360 S.A.C.',            services: 'Selección de personal técnico para industria y logística', experience: '7',          location: 'Chancay / Huaral',        created_at: '2026-03-03T13:30:00Z' },
  { id: 47, clerk_user_id: 'mock-v-13', role: 'proveedor', fullname: 'César Rueda Palomino',       email: 'crueda@geodataperu.pe',      company_name: 'Geodata Perú S.A.C.',                   services: 'Levantamientos topográficos, estudios de suelo y geotecnia', experience: '17',    location: 'Lima / Chancay / Ica',    created_at: '2026-03-15T10:00:00Z' },
  { id: 48, clerk_user_id: 'mock-v-14', role: 'proveedor', fullname: 'Verónica Lazo Bermúdez',     email: 'vlazo@comunicaportu.pe',     company_name: 'ComunicaPortu S.A.C.',                  services: 'Telecomunicaciones y redes para zonas industriales', experience: '11',               location: 'Chancay',                 created_at: '2026-03-25T14:45:00Z' },
  { id: 49, clerk_user_id: 'mock-v-15', role: 'proveedor', fullname: 'Raúl Espinoza Díaz',         email: 'respinoza@ingmecanica.pe',   company_name: 'Ingeniería Mecánica Industrial S.A.C.',  services: 'Diseño y fabricación de estructuras metálicas y equipos', experience: '19',        location: 'Lima / Chancay',          created_at: '2026-04-05T09:00:00Z' },
  { id: 50, clerk_user_id: 'mock-v-16', role: 'proveedor', fullname: 'Mónica Arce Vidal',          email: 'marce@innoport.pe',          company_name: 'InnoPort Tech S.A.C.',                  services: 'Drones, IA y automatización para operaciones portuarias', experience: '5',         location: 'Chancay / Lima',          created_at: '2026-04-20T11:15:00Z' },
];

export const getDevMatchesForProfile = (profile: AppUserProfile) => {
  if (profile.role === 'empresa') {
    return DEV_MOCK_USERS.filter(u => u.role === 'propietario' || u.role === 'proveedor');
  }
  if (profile.role === 'propietario' || profile.role === 'proveedor') {
    return DEV_MOCK_USERS.filter(u => u.role === 'empresa');
  }
  return DEV_MOCK_USERS;
};
